name: electron-cgi-calculator-demo
version: '0.1'
summary: Electron CGI Calculator Demo
description: |
  Simple Calculator using Electron CGI
base: core18
confinement: strict
grade: devel

apps:
  electron-cgi-calculator-demo:
    command: desktop-launch "$SNAP/electron-cgi-calculator-demo/node-calculator" "--no-sandbox"
    plugs:
    - browser-support
    - network
    - network-bind
    - opengl
    - pulseaudio
    - x11

parts:
  dot-net-calculator:
    plugin: dotnet
    source: ./DotNetCalculator
    after: [node-calculator]
    build-snaps:
    - dotnet-sdk/3.1/stable
    stage-snaps:
    - dotnet-sdk/3.1/stable

  node-calculator:
    plugin: nodejs
    nodejs-package-manager: npm
    source: ./NodeCalculator
    build-packages:
    - nodejs
    - npm
    - unzip
    stage-packages:
    - nodejs
    - npm
    - unzip
    - libasound2
    - libgconf-2-4
    - libnss3
    - libx11-xcb1
    - libxss1
    - libxtst6
